version: 0.1

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - npm install
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - npm run build
      # - command
  post_build:
    commands:
      - aws s3 sync --delete build s3://shopping-basket --cache-control max-age=3600
